import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { Activity } from '../registry/types.js'

export interface EnvContext {
  walletAddress?: string
}

/**
 * Write a .env.example file to the scaffolded project. Template-supplied
 * .env.example (if any) takes precedence — callers should only run this
 * when no template-level file exists, or to augment metadata.
 */
export async function writeEnvExample(
  projectDir: string,
  activity: Activity,
  ctx: EnvContext = {}
): Promise<void> {
  const lines: string[] = [
    '# Generated by @human.tech/create-agent-wallet',
    `# Activity: ${activity.name} (${activity.slug})`
  ]
  if (ctx.walletAddress) lines.push(`# Wallet: ${ctx.walletAddress}`)
  lines.push('')

  if (activity.envVars.length === 0) {
    lines.push('# No required env vars for this activity.')
    lines.push('# Add your own below.')
    lines.push('')
  } else {
    for (const v of activity.envVars) {
      if (v.description) lines.push(`# ${v.description}`)
      const value = v.default ?? ''
      const commentPrefix = v.required ? '' : '# '
      lines.push(`${commentPrefix}${v.key}=${value}`)
      lines.push('')
    }
  }

  await writeFile(join(projectDir, '.env.example'), lines.join('\n'))
}
